### ISSUE TITLE
Parametro -a permite suporte a apenas um array

### ISSUE THREAD

**Issue by evandrogdn** [maviniciuus/af-scaffolder#1]
Tive um caso, onde necessitava estar passando mais de um array com parâmetros para ser usado dentro do meu template, porém com a opção -a, estou conseguindo passar apenas um array para ser usado. Teria alguma outra maneira de poder estar passando mais de um array?

**Comment by maviniciuus** [comment]
Com o suporte a json de parâmetros essa necessidade fica suprimida, caberia um bom PR para adicionar o uso de json arguments na DOC.
